### PR TITLE
add zone raiders stylesheet

### PR DESCRIPTION
**Pull request by DanieleSuppo**
Add the stylesheet for a game called Zone Raiders https://zoneraiders.com/

You can test with the roster attached (I renamed it .zip because of github)
[Reclaimers.zip](https://github.com/DaeronAlagos/rostercards/files/12372972/Reclaimers.zip)

### CODE REVIEW

**Comment by DaeronAlagos** [comment]
Thank you for the submission. I've checked out the branch locally and the rendered template looks really good.

I'm not going to review line-by-line as I don't think that adds much value at this time. I do have some more general comments though.

- **Print version looks great**. Excellent work on this. I found getting the print version right, the hardest part.
- Have you considered/are concerned with, how it looks on **desktop and mobile**? The desktop view is usable, but I found viewing on mobile difficult. My original thoughts around the stylesheets (see me old repos) was always for them to be printed. I have since considered having them viewable on mobile might also add value for some users.
- **Inline styles**. Similar to my older repos, this uses inline styles. Roster Cards includes the tailwindcss framework, which is used for the main site, and also in the existing xslts. I don't suggest you refactor now, but if you decide to consider non-print versions, you might find this helpful for css styling across multiple medias.
- **Promote it**. An addition I would recommend now is to add Zone Raiders to the supported games list. The edit is made in `Main.elm`. See snippet/suggestion below.

```
-- Main.elm (lines 321-323)
[ li [] [ text "Stargrave" ]
, li [] [ text "Xenos Rampant" ]
, li [] [ text "Zone Raiders" ]
]
```

**Review by DaeronAlagos — APPROVED** [review]
Approved. Please see general comments in case you wish to push any additional changes before merging.

**Comment by DanieleSuppo** [comment]
Sorry for the late reply, I'm still in vacation for few more days.
Thanks for approval, if we are not in rush (and I think not) maybe I can try to do the change to the elm file before the merge, just to learn the ropes on it.

You did great suggestions, for future upgrades I will check you stylesheets and see how can I deal with desktop / mobile versions, it's a use case I have not considered but I feel in 2023 it makes sense to not print anymore ;)

Cheers
Daniele

**Comment by DaeronAlagos** [comment]
I'm going to merge this so it's available for everyone to use. We can iterate on it with improvements in the future.

**Pull request merged**
